# runtime: nodejs
# env: flex
runtime: nodejs12
# instance_class: F2
# env: flex

# automatic_scaling:
#   min_num_instances: 2
#   max_num_instances: 20
#   cpu_utilization:
#     target_utilization: 0.75